### ISSUE TITLE
Should validation be on FE?

### ISSUE THREAD

**Issue by kenpaicat** [SloveniaEngineering/laguna-frontend#28]
## Description

Feels wrong to do validation on two different places.
cc @amadejzr @zigapovhe @anzbez

**Comment by zigapovhe** [comment]
If validation rules are the same, I don't see a problem with having validation both on FE and BE. 
Why I think validation should be on FE:
- Instant feedback to the user
- It is a first line of defense to reduce unnecessary requests to API.

Why I think having validation on BE is still a good idea:
- To prevent invalid state if request is sent via POSTMAN, CURL or similar HTTP Testing tools (example: password with 1 char on registration)
- Catch badly written FE validation rules

**Comment by kenpaicat** [comment]
82436b5094b39622017a02e9f7ecf8ea636d3f2d reduces password constraints on FE because backend doesn't enforce them. Backend checks for length and non-control-char.

Validation will be favored on BE since Error messages are coming from BE, but some validation (to prevent common mistakes and thus burdening BE with them) can be enforced on FE (such as PWD length).
