### ISSUE TITLE
[FE] Auto-fill support on login

### ISSUE THREAD

**Issue by kenpaicat** [SloveniaEngineering/laguna-frontend#29]
## Description

Login screen should support auto-fill features for autofilling with various password managers

**Comment by zigapovhe** [comment]
Alright, CredentialTextField does support this, but I forgot to add AutofillGroup widget on LoginScreen.dart as parent widget of those CredentionTextFields. @amadejzr @Quiirex Let me know which one of you wants to fix that. After adding this widget, please test if it works as expected with password manager of your choice

**Comment by Quiirex** [comment]
> Alright, CredentialTextField does support this, but I forgot to add AutofillGroup widget on LoginScreen.dart as parent widget of those CredentionTextFields. @amadejzr @Quiirex @anzbez Let me know which one of you wants to fix that. After adding this widget, please test if it works as expected with password manager of your choice

I can look into it.

**Comment by zigapovhe** [comment]
no problem :D. Thanks for the idea about auto-login haha. I think it we should discuss it in another issue.
